# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99c25caafc3034450c477e2cf8261669396d252f2e86fc382bf3857a6faa05e9be22635eda4b4e56b697cf2ef5f4bec0a2a72118e9e8d9a03d0740043a15e69d
  stripe_publishable_key: pk_test_Uinl9l2IPTmEvf5RZgoupGKt
  stripe_secret_key: sk_test_t7hEJGSWDq8R2yfb9O3rWBQ6

test:
  secret_key_base: c1a60e27b2d339fc258d51a1d00c402862930df208b88e475851e798bc918184fc9d67caad2121c307a86490992c1208964be5fe669be42fd945f6e413a1ab7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: pk_test_Uinl9l2IPTmEvf5RZgoupGKt
  stripe_secret_key: sk_test_t7hEJGSWDq8R2yfb9O3rWBQ6
